/**
 * Extra foods: ingredients ~ China food composition public values;
 * cooked dishes = recipe averages (oil varies a lot). For diary estimate only.
 */
module.exports = [
  {"id": "staple_201", "cat": "staple", "name": "小米粥", "aliases": "小米 小米稀饭", "kcal": 46, "protein": 1.4, "fat": 0.7, "carb": 8.4, "portion": 250},
  {"id": "staple_202", "cat": "staple", "name": "花卷", "aliases": "馒头花卷", "kcal": 213, "protein": 6.4, "fat": 1.4, "carb": 44, "portion": 80},
  {"id": "staple_203", "cat": "staple", "name": "烧饼", "aliases": "芝麻烧饼 火烧", "kcal": 295, "protein": 9.5, "fat": 7.5, "carb": 48, "portion": 80},
  {"id": "staple_204", "cat": "staple", "name": "煎饼", "aliases": "杂粮煎饼 鸡蛋煎饼", "kcal": 220, "protein": 7, "fat": 6, "carb": 34, "portion": 150},
  {"id": "staple_205", "cat": "staple", "name": "手抓饼", "aliases": "葱油饼 飞饼", "kcal": 310, "protein": 5.5, "fat": 15, "carb": 38, "portion": 100},
  {"id": "staple_206", "cat": "staple", "name": "河粉(煮)", "aliases": "沙河粉 粿条", "kcal": 109, "protein": 1.8, "fat": 0.2, "carb": 25, "portion": 200},
  {"id": "staple_207", "cat": "staple", "name": "粉丝(煮)", "aliases": "红薯粉丝 粉条", "kcal": 84, "protein": 0.2, "fat": 0.1, "carb": 20.5, "portion": 100},
  {"id": "staple_208", "cat": "staple", "name": "乌冬面(煮)", "aliases": "乌冬", "kcal": 105, "protein": 2.6, "fat": 0.4, "carb": 22, "portion": 200},
  {"id": "staple_209", "cat": "staple", "name": "荞麦面(煮)", "aliases": "荞麦面条", "kcal": 114, "protein": 4.5, "fat": 0.7, "carb": 22, "portion": 200},
  {"id": "staple_210", "cat": "staple", "name": "糯米饭", "aliases": "江米 糯米", "kcal": 116, "protein": 2.7, "fat": 0.3, "carb": 25.8, "portion": 150},
  {"id": "staple_211", "cat": "staple", "name": "粽子(鲜肉)", "aliases": "肉粽", "kcal": 210, "protein": 6.5, "fat": 5, "carb": 35, "portion": 100},
  {"id": "staple_212", "cat": "staple", "name": "汤圆(黑芝麻)", "aliases": "元宵", "kcal": 310, "protein": 5, "fat": 8, "carb": 54, "portion": 80},
  {"id": "staple_213", "cat": "staple", "name": "紫薯", "aliases": "地瓜紫", "kcal": 82, "protein": 1.3, "fat": 0.1, "carb": 19.5, "portion": 150},
  {"id": "staple_214", "cat": "staple", "name": "山药", "aliases": "淮山", "kcal": 56, "protein": 1.9, "fat": 0.2, "carb": 12.4, "portion": 100},
  {"id": "staple_215", "cat": "staple", "name": "芋头", "aliases": "芋艿", "kcal": 79, "protein": 2.2, "fat": 0.2, "carb": 18.1, "portion": 100},
  {"id": "staple_216", "cat": "staple", "name": "藜麦(煮)", "aliases": "奎奴亚藜", "kcal": 120, "protein": 4.4, "fat": 1.9, "carb": 21.3, "portion": 150},
  {"id": "staple_217", "cat": "staple", "name": "玉米面窝头", "aliases": "窝窝头", "kcal": 212, "protein": 7.5, "fat": 2.5, "carb": 42, "portion": 80},
  {"id": "staple_218", "cat": "staple", "name": "三明治(火腿蛋)", "aliases": "火腿三明治", "kcal": 250, "protein": 11, "fat": 10, "carb": 28, "portion": 150},
  {"id": "staple_219", "cat": "staple", "name": "麦片冲调(已冲)", "aliases": "即食麦片 牛奶麦片", "kcal": 80, "protein": 3, "fat": 1.5, "carb": 14, "portion": 250},
  {"id": "staple_220", "cat": "staple", "name": "春卷(炸)", "aliases": "春卷", "kcal": 250, "protein": 5, "fat": 12, "carb": 30, "portion": 60},
  {"id": "meat_201", "cat": "meat", "name": "五花肉", "aliases": "猪五花 五花", "kcal": 395, "protein": 13.2, "fat": 37, "carb": 0, "portion": 80},
  {"id": "meat_202", "cat": "meat", "name": "猪里脊", "aliases": "里脊肉 瘦里脊", "kcal": 155, "protein": 20.2, "fat": 7.9, "carb": 0, "portion": 100},
  {"id": "meat_203", "cat": "meat", "name": "牛腩", "aliases": "炖牛腩", "kcal": 192, "protein": 18.6, "fat": 12.7, "carb": 0, "portion": 100},
  {"id": "meat_204", "cat": "meat", "name": "牛里脊", "aliases": "菲力 瘦牛肉", "kcal": 122, "protein": 20.5, "fat": 4.2, "carb": 0, "portion": 100},
  {"id": "meat_205", "cat": "meat", "name": "带鱼", "aliases": "带鱼段", "kcal": 127, "protein": 17.7, "fat": 4.9, "carb": 0, "portion": 100},
  {"id": "meat_206", "cat": "meat", "name": "鲈鱼", "aliases": "海鲈 鲈鱼片", "kcal": 105, "protein": 18.6, "fat": 3.4, "carb": 0, "portion": 100},
  {"id": "meat_207", "cat": "meat", "name": "黄鱼", "aliases": "小黄鱼", "kcal": 97, "protein": 17.9, "fat": 2.5, "carb": 0, "portion": 100},
  {"id": "meat_208", "cat": "meat", "name": "鱿鱼(鲜)", "aliases": "鱿鱼须 鲜鱿", "kcal": 75, "protein": 15.2, "fat": 0.6, "carb": 2.4, "portion": 100},
  {"id": "meat_209", "cat": "meat", "name": "扇贝", "aliases": "瑶柱鲜 扇贝柱", "kcal": 60, "protein": 11.1, "fat": 0.6, "carb": 2.6, "portion": 80},
  {"id": "meat_210", "cat": "meat", "name": "蛤蜊", "aliases": "花蛤 蛤蜊肉", "kcal": 62, "protein": 10.1, "fat": 1.1, "carb": 2.8, "portion": 80},
  {"id": "meat_211", "cat": "meat", "name": "鸭肉", "aliases": "鸭腿 鸭胸", "kcal": 240, "protein": 15.5, "fat": 19.7, "carb": 0, "portion": 100},
  {"id": "meat_212", "cat": "meat", "name": "鸡胗", "aliases": "鸡肫", "kcal": 118, "protein": 19.2, "fat": 4.2, "carb": 1.3, "portion": 50},
  {"id": "meat_213", "cat": "meat", "name": "猪肝", "aliases": "肝", "kcal": 129, "protein": 19.3, "fat": 3.5, "carb": 5, "portion": 80},
  {"id": "meat_214", "cat": "meat", "name": "午餐肉", "aliases": "罐头午餐肉", "kcal": 229, "protein": 12.5, "fat": 18.5, "carb": 4, "portion": 40},
  {"id": "meat_215", "cat": "meat", "name": "酱牛肉", "aliases": "卤牛肉", "kcal": 246, "protein": 31.4, "fat": 11.9, "carb": 0, "portion": 50},
  {"id": "meat_216", "cat": "meat", "name": "烤鸭", "aliases": "北京烤鸭", "kcal": 436, "protein": 16.6, "fat": 38.4, "carb": 6, "portion": 80},
  {"id": "meat_217", "cat": "meat", "name": "皮蛋", "aliases": "松花蛋 变蛋", "kcal": 171, "protein": 14.2, "fat": 10.7, "carb": 4.5, "portion": 50},
  {"id": "meat_218", "cat": "meat", "name": "咸鸭蛋", "aliases": "咸蛋", "kcal": 190, "protein": 12.7, "fat": 12.7, "carb": 4.7, "portion": 50},
  {"id": "meat_219", "cat": "meat", "name": "虾仁", "aliases": "去壳虾", "kcal": 93, "protein": 18.6, "fat": 0.8, "carb": 2.8, "portion": 80},
  {"id": "meat_220", "cat": "meat", "name": "鸡蛋(煎)", "aliases": "煎蛋 荷包蛋", "kcal": 196, "protein": 13.6, "fat": 15, "carb": 1.1, "portion": 50},
  {"id": "dairy_201", "cat": "dairy", "name": "低脂牛奶", "aliases": "半脱脂奶", "kcal": 46, "protein": 3.3, "fat": 1.5, "carb": 4.8, "portion": 250},
  {"id": "dairy_202", "cat": "dairy", "name": "豆奶(原味)", "aliases": "豆奶饮料", "kcal": 30, "protein": 1.5, "fat": 1, "carb": 3.5, "portion": 250},
  {"id": "dairy_203", "cat": "dairy", "name": "内酯豆腐", "aliases": "盒装嫩豆腐 绢豆腐", "kcal": 49, "protein": 5, "fat": 2.5, "carb": 1.5, "portion": 100},
  {"id": "dairy_204", "cat": "dairy", "name": "腐竹", "aliases": "油皮", "kcal": 459, "protein": 44.6, "fat": 21.7, "carb": 22.3, "portion": 20},
  {"id": "dairy_205", "cat": "dairy", "name": "千张", "aliases": "百叶 豆皮", "kcal": 260, "protein": 24.5, "fat": 16, "carb": 4.5, "portion": 50},
  {"id": "dairy_206", "cat": "dairy", "name": "脱脂酸奶", "aliases": "无脂肪酸奶", "kcal": 45, "protein": 4.5, "fat": 0.2, "carb": 6.5, "portion": 150},
  {"id": "dairy_207", "cat": "dairy", "name": "黄豆(干)", "aliases": "大豆", "kcal": 390, "protein": 35, "fat": 16, "carb": 18.7, "portion": 30},
  {"id": "dairy_208", "cat": "dairy", "name": "黑豆(干)", "aliases": "黑大豆", "kcal": 381, "protein": 36, "fat": 15.9, "carb": 23.3, "portion": 30},
  {"id": "dairy_209", "cat": "dairy", "name": "红豆(煮)", "aliases": "赤小豆 蜜红豆", "kcal": 116, "protein": 6.7, "fat": 0.4, "carb": 21.5, "portion": 80},
  {"id": "dairy_210", "cat": "dairy", "name": "绿豆(煮)", "aliases": "煮绿豆", "kcal": 105, "protein": 7.5, "fat": 0.4, "carb": 18, "portion": 80},
  {"id": "dairy_211", "cat": "dairy", "name": "鹰嘴豆(煮)", "aliases": "加尔班佐豆", "kcal": 164, "protein": 8.9, "fat": 2.6, "carb": 27.4, "portion": 80},
  {"id": "dairy_212", "cat": "dairy", "name": "杏仁奶", "aliases": "杏仁露", "kcal": 24, "protein": 0.5, "fat": 1.1, "carb": 3, "portion": 250},
  {"id": "veg_201", "cat": "veg", "name": "油麦菜", "aliases": "莴苣叶", "kcal": 15, "protein": 1.4, "fat": 0.4, "carb": 2.1, "portion": 100},
  {"id": "veg_202", "cat": "veg", "name": "空心菜", "aliases": "蕹菜 通菜", "kcal": 20, "protein": 2.2, "fat": 0.3, "carb": 3.1, "portion": 100},
  {"id": "veg_203", "cat": "veg", "name": "菜心", "aliases": "菜薹 广东菜心", "kcal": 24, "protein": 2.2, "fat": 0.4, "carb": 3.6, "portion": 100},
  {"id": "veg_204", "cat": "veg", "name": "芥蓝", "aliases": "芥兰花", "kcal": 24, "protein": 2.8, "fat": 0.4, "carb": 3.3, "portion": 100},
  {"id": "veg_205", "cat": "veg", "name": "韭菜", "aliases": "韭黄", "kcal": 26, "protein": 2.4, "fat": 0.4, "carb": 3.2, "portion": 80},
  {"id": "veg_206", "cat": "veg", "name": "苦瓜", "aliases": "凉瓜", "kcal": 19, "protein": 1, "fat": 0.1, "carb": 3.5, "portion": 100},
  {"id": "veg_207", "cat": "veg", "name": "丝瓜", "aliases": "水瓜", "kcal": 20, "protein": 1, "fat": 0.2, "carb": 3.6, "portion": 100},
  {"id": "veg_208", "cat": "veg", "name": "西葫芦", "aliases": "角瓜 茭瓜", "kcal": 18, "protein": 0.8, "fat": 0.2, "carb": 3.3, "portion": 100},
  {"id": "veg_209", "cat": "veg", "name": "白萝卜", "aliases": "萝卜", "kcal": 16, "protein": 0.7, "fat": 0.1, "carb": 3.4, "portion": 100},
  {"id": "veg_210", "cat": "veg", "name": "竹笋", "aliases": "春笋 笋尖", "kcal": 19, "protein": 2.6, "fat": 0.2, "carb": 1.8, "portion": 80},
  {"id": "veg_211", "cat": "veg", "name": "木耳(泡发)", "aliases": "黑木耳", "kcal": 21, "protein": 1.5, "fat": 0.2, "carb": 3.5, "portion": 50},
  {"id": "veg_212", "cat": "veg", "name": "银耳(泡发)", "aliases": "白木耳", "kcal": 27, "protein": 1.2, "fat": 0.1, "carb": 5.5, "portion": 50},
  {"id": "veg_213", "cat": "veg", "name": "香菇(鲜)", "aliases": "花菇", "kcal": 26, "protein": 2.2, "fat": 0.3, "carb": 4.2, "portion": 50},
  {"id": "veg_214", "cat": "veg", "name": "金针菇", "aliases": "海鲜菇类", "kcal": 32, "protein": 2.4, "fat": 0.4, "carb": 5.3, "portion": 50},
  {"id": "veg_215", "cat": "veg", "name": "杏鲍菇", "aliases": "刺芹菇", "kcal": 31, "protein": 1.3, "fat": 0.1, "carb": 6.2, "portion": 80},
  {"id": "veg_216", "cat": "veg", "name": "秋葵", "aliases": "羊角豆", "kcal": 37, "protein": 2, "fat": 0.1, "carb": 7.5, "portion": 80},
  {"id": "veg_217", "cat": "veg", "name": "芦笋", "aliases": "石刁柏", "kcal": 18, "protein": 1.4, "fat": 0.1, "carb": 3, "portion": 80},
  {"id": "veg_218", "cat": "veg", "name": "花菜", "aliases": "菜花 花椰菜", "kcal": 24, "protein": 2.1, "fat": 0.2, "carb": 4.3, "portion": 100},
  {"id": "veg_219", "cat": "veg", "name": "四季豆", "aliases": "豆角 芸豆", "kcal": 28, "protein": 2, "fat": 0.4, "carb": 4.9, "portion": 100},
  {"id": "veg_220", "cat": "veg", "name": "豌豆", "aliases": "青豌豆", "kcal": 105, "protein": 7.4, "fat": 0.3, "carb": 18.2, "portion": 80},
  {"id": "veg_221", "cat": "veg", "name": "玉米粒(煮)", "aliases": "甜玉米粒", "kcal": 112, "protein": 4, "fat": 1.2, "carb": 22.8, "portion": 80},
  {"id": "veg_222", "cat": "veg", "name": "莴笋", "aliases": "青笋 莴苣茎", "kcal": 14, "protein": 1, "fat": 0.1, "carb": 2.2, "portion": 100},
  {"id": "veg_223", "cat": "veg", "name": "荷兰豆", "aliases": "甜豆", "kcal": 27, "protein": 2.5, "fat": 0.3, "carb": 4.1, "portion": 80},
  {"id": "veg_224", "cat": "veg", "name": "蒜苗", "aliases": "青蒜", "kcal": 34, "protein": 2.1, "fat": 0.4, "carb": 6.2, "portion": 50},
  {"id": "fruit_201", "cat": "fruit", "name": "橘子", "aliases": "桔子 蜜橘", "kcal": 44, "protein": 0.7, "fat": 0.2, "carb": 10.2, "portion": 120},
  {"id": "fruit_202", "cat": "fruit", "name": "柠檬", "aliases": "青柠", "kcal": 35, "protein": 1.1, "fat": 1.2, "carb": 4.9, "portion": 50},
  {"id": "fruit_203", "cat": "fruit", "name": "菠萝", "aliases": "凤梨", "kcal": 44, "protein": 0.5, "fat": 0.1, "carb": 10.8, "portion": 150},
  {"id": "fruit_204", "cat": "fruit", "name": "哈密瓜", "aliases": "甜瓜 香瓜类", "kcal": 34, "protein": 0.5, "fat": 0.1, "carb": 7.9, "portion": 150},
  {"id": "fruit_205", "cat": "fruit", "name": "木瓜", "aliases": "番木瓜", "kcal": 29, "protein": 0.4, "fat": 0.1, "carb": 7, "portion": 150},
  {"id": "fruit_206", "cat": "fruit", "name": "荔枝", "aliases": "妃子笑", "kcal": 70, "protein": 0.9, "fat": 0.2, "carb": 16.6, "portion": 80},
  {"id": "fruit_207", "cat": "fruit", "name": "龙眼", "aliases": "桂圆鲜", "kcal": 71, "protein": 1.2, "fat": 0.1, "carb": 16.6, "portion": 80},
  {"id": "fruit_208", "cat": "fruit", "name": "石榴", "aliases": "石榴籽", "kcal": 63, "protein": 1.3, "fat": 0.2, "carb": 14.5, "portion": 100},
  {"id": "fruit_209", "cat": "fruit", "name": "桑葚", "aliases": "黑桑葚", "kcal": 54, "protein": 1.6, "fat": 0.4, "carb": 12, "portion": 80},
  {"id": "fruit_210", "cat": "fruit", "name": "椰子肉", "aliases": "鲜椰肉", "kcal": 241, "protein": 4, "fat": 22, "carb": 10, "portion": 40},
  {"id": "fruit_211", "cat": "fruit", "name": "山楂", "aliases": "红果", "kcal": 102, "protein": 0.5, "fat": 0.6, "carb": 25, "portion": 50},
  {"id": "fruit_212", "cat": "fruit", "name": "杨梅", "aliases": "红杨梅", "kcal": 30, "protein": 0.8, "fat": 0.2, "carb": 6.7, "portion": 80},
  {"id": "fruit_213", "cat": "fruit", "name": "李子", "aliases": "布林", "kcal": 36, "protein": 0.7, "fat": 0.2, "carb": 8.5, "portion": 80},
  {"id": "fruit_214", "cat": "fruit", "name": "杏", "aliases": "杏子", "kcal": 36, "protein": 0.9, "fat": 0.1, "carb": 7.8, "portion": 80},
  {"id": "fruit_215", "cat": "fruit", "name": "百香果", "aliases": "热情果", "kcal": 97, "protein": 2.2, "fat": 0.7, "carb": 22, "portion": 50},
  {"id": "fruit_216", "cat": "fruit", "name": "山竹", "aliases": "山竺", "kcal": 73, "protein": 0.4, "fat": 0.2, "carb": 18, "portion": 80},
  {"id": "snack_201", "cat": "snack", "name": "腰果", "aliases": "焗腰果", "kcal": 552, "protein": 17.3, "fat": 36.7, "carb": 41.6, "portion": 20},
  {"id": "snack_202", "cat": "snack", "name": "开心果", "aliases": "阿月浑子", "kcal": 594, "protein": 20.6, "fat": 45.4, "carb": 27.7, "portion": 20},
  {"id": "snack_203", "cat": "snack", "name": "葡萄干", "aliases": "提子干", "kcal": 341, "protein": 2.5, "fat": 0.4, "carb": 81.8, "portion": 20},
  {"id": "snack_204", "cat": "snack", "name": "红枣(干)", "aliases": "大枣 灰枣", "kcal": 264, "protein": 3.2, "fat": 0.5, "carb": 67.8, "portion": 20},
  {"id": "snack_205", "cat": "snack", "name": "肉松", "aliases": "猪肉松", "kcal": 396, "protein": 25, "fat": 12, "carb": 48, "portion": 15},
  {"id": "snack_206", "cat": "snack", "name": "猪肉脯", "aliases": "肉干脯", "kcal": 379, "protein": 30, "fat": 9, "carb": 42, "portion": 15},
  {"id": "snack_207", "cat": "snack", "name": "曲奇", "aliases": "黄油曲奇", "kcal": 546, "protein": 5.5, "fat": 31, "carb": 62, "portion": 20},
  {"id": "snack_208", "cat": "snack", "name": "威化饼干", "aliases": "威化", "kcal": 500, "protein": 6, "fat": 25, "carb": 62, "portion": 20},
  {"id": "snack_209", "cat": "snack", "name": "爆米花(甜)", "aliases": "焦糖爆米花", "kcal": 459, "protein": 7, "fat": 14, "carb": 74, "portion": 30},
  {"id": "snack_210", "cat": "snack", "name": "海苔", "aliases": "紫菜零食", "kcal": 25, "protein": 4, "fat": 0.5, "carb": 2, "portion": 5},
  {"id": "snack_211", "cat": "snack", "name": "辣条", "aliases": "大辣片", "kcal": 500, "protein": 8, "fat": 28, "carb": 52, "portion": 30},
  {"id": "snack_212", "cat": "snack", "name": "月饼(广式莲蓉)", "aliases": "莲蓉月饼", "kcal": 405, "protein": 5.5, "fat": 15, "carb": 63, "portion": 50},
  {"id": "snack_213", "cat": "snack", "name": "蛋黄派", "aliases": "注心派", "kcal": 440, "protein": 5, "fat": 22, "carb": 56, "portion": 40},
  {"id": "snack_214", "cat": "snack", "name": "果冻", "aliases": "果冻布丁", "kcal": 70, "protein": 0.1, "fat": 0, "carb": 17, "portion": 50},
  {"id": "drink_201", "cat": "drink", "name": "白开水", "aliases": "矿泉水 纯净水", "kcal": 0, "protein": 0, "fat": 0, "carb": 0, "portion": 250},
  {"id": "drink_202", "cat": "drink", "name": "无糖可乐", "aliases": "零度可乐 健怡", "kcal": 1, "protein": 0, "fat": 0, "carb": 0, "portion": 250},
  {"id": "drink_203", "cat": "drink", "name": "雪碧", "aliases": "柠檬汽水", "kcal": 43, "protein": 0, "fat": 0, "carb": 10.6, "portion": 250},
  {"id": "drink_204", "cat": "drink", "name": "美式咖啡", "aliases": "黑咖啡美式", "kcal": 3, "protein": 0.2, "fat": 0, "carb": 0, "portion": 240},
  {"id": "drink_205", "cat": "drink", "name": "卡布奇诺", "aliases": "卡布", "kcal": 50, "protein": 2.5, "fat": 2, "carb": 5, "portion": 180},
  {"id": "drink_206", "cat": "drink", "name": "椰汁", "aliases": "椰子汁 椰奶饮", "kcal": 50, "protein": 0.5, "fat": 2.5, "carb": 6, "portion": 250},
  {"id": "drink_207", "cat": "drink", "name": "红牛", "aliases": "功能饮料", "kcal": 45, "protein": 0, "fat": 0, "carb": 11, "portion": 250},
  {"id": "drink_208", "cat": "drink", "name": "黄酒", "aliases": "料酒黄酒 绍兴酒", "kcal": 66, "protein": 0.5, "fat": 0, "carb": 3.5, "portion": 50},
  {"id": "drink_209", "cat": "drink", "name": "米酒", "aliases": "醪糟 甜酒酿", "kcal": 90, "protein": 1.5, "fat": 0.5, "carb": 18, "portion": 50},
  {"id": "drink_210", "cat": "drink", "name": "醋", "aliases": "陈醋 米醋", "kcal": 31, "protein": 0.3, "fat": 0, "carb": 4.9, "portion": 10},
  {"id": "drink_211", "cat": "drink", "name": "蚝油", "aliases": "耗油", "kcal": 120, "protein": 4, "fat": 0.5, "carb": 24, "portion": 10},
  {"id": "drink_212", "cat": "drink", "name": "芝麻酱", "aliases": "麻酱", "kcal": 622, "protein": 19.2, "fat": 52.7, "carb": 18.4, "portion": 15},
  {"id": "drink_213", "cat": "drink", "name": "花生酱", "aliases": "颗粒花生酱", "kcal": 594, "protein": 20, "fat": 50, "carb": 22, "portion": 15},
  {"id": "drink_214", "cat": "drink", "name": "沙拉酱", "aliases": "蛋黄酱 mayo", "kcal": 680, "protein": 1, "fat": 75, "carb": 5, "portion": 15},
  {"id": "drink_215", "cat": "drink", "name": "甜面酱", "aliases": "京酱", "kcal": 136, "protein": 4.5, "fat": 0.5, "carb": 28, "portion": 15},
  {"id": "drink_216", "cat": "drink", "name": "辣椒酱", "aliases": "剁椒 蒜蓉辣酱", "kcal": 50, "protein": 1.5, "fat": 2, "carb": 7, "portion": 10},
  {"id": "drink_217", "cat": "drink", "name": "红糖", "aliases": "黑糖", "kcal": 389, "protein": 0.7, "fat": 0, "carb": 98, "portion": 10},
  {"id": "drink_218", "cat": "drink", "name": "料酒", "aliases": "黄酒料酒", "kcal": 60, "protein": 0.3, "fat": 0, "carb": 2, "portion": 10},
  {"id": "dish_201", "cat": "dish", "name": "蒜蓉空心菜", "aliases": "清炒空心菜", "kcal": 55, "protein": 2, "fat": 3.5, "carb": 4, "portion": 150},
  {"id": "dish_202", "cat": "dish", "name": "鱼香茄子", "aliases": "茄子煲", "kcal": 130, "protein": 2.5, "fat": 9, "carb": 10, "portion": 180},
  {"id": "dish_203", "cat": "dish", "name": "红烧带鱼", "aliases": "炸带鱼红烧", "kcal": 220, "protein": 16, "fat": 15, "carb": 4, "portion": 120},
  {"id": "dish_204", "cat": "dish", "name": "清蒸鲈鱼", "aliases": "清蒸鱼", "kcal": 110, "protein": 18, "fat": 4, "carb": 1, "portion": 200},
  {"id": "dish_205", "cat": "dish", "name": "蒜蓉粉丝蒸虾", "aliases": "粉丝虾", "kcal": 120, "protein": 12, "fat": 4, "carb": 10, "portion": 150},
  {"id": "dish_206", "cat": "dish", "name": "干锅花菜", "aliases": "干锅菜花", "kcal": 95, "protein": 3, "fat": 6, "carb": 7, "portion": 180},
  {"id": "dish_207", "cat": "dish", "name": "蒜蓉油麦菜", "aliases": "清炒油麦菜", "kcal": 50, "protein": 1.5, "fat": 3.5, "carb": 3, "portion": 150},
  {"id": "dish_208", "cat": "dish", "name": "西红柿炒鸡蛋", "aliases": "番茄炒鸡蛋 西红柿炒蛋", "kcal": 110, "protein": 6.5, "fat": 7, "carb": 5, "portion": 150},
  {"id": "dish_209", "cat": "dish", "name": "芹菜炒肉", "aliases": "芹菜肉丝", "kcal": 120, "protein": 9, "fat": 7, "carb": 5, "portion": 150},
  {"id": "dish_210", "cat": "dish", "name": "土豆炖排骨", "aliases": "排骨炖土豆", "kcal": 160, "protein": 11, "fat": 9, "carb": 8, "portion": 200},
  {"id": "dish_211", "cat": "dish", "name": "红烧鸡块", "aliases": "烧鸡块", "kcal": 180, "protein": 16, "fat": 11, "carb": 3, "portion": 150},
  {"id": "dish_212", "cat": "dish", "name": "酱爆鸡丁", "aliases": "鸡丁", "kcal": 170, "protein": 15, "fat": 10, "carb": 5, "portion": 150},
  {"id": "dish_213", "cat": "dish", "name": "尖椒干豆腐", "aliases": "干豆腐炒尖椒", "kcal": 140, "protein": 10, "fat": 9, "carb": 5, "portion": 150},
  {"id": "dish_214", "cat": "dish", "name": "酸辣粉", "aliases": "重庆酸辣粉", "kcal": 140, "protein": 3, "fat": 4, "carb": 24, "portion": 300},
  {"id": "dish_215", "cat": "dish", "name": "凉皮", "aliases": "陕西凉皮", "kcal": 120, "protein": 3.5, "fat": 2, "carb": 23, "portion": 250},
  {"id": "dish_216", "cat": "dish", "name": "肉夹馍", "aliases": "腊汁肉夹馍", "kcal": 250, "protein": 11, "fat": 10, "carb": 30, "portion": 200},
  {"id": "dish_217", "cat": "dish", "name": "煎饼果子", "aliases": "鸡蛋煎饼果子", "kcal": 220, "protein": 8, "fat": 8, "carb": 28, "portion": 200},
  {"id": "dish_218", "cat": "dish", "name": "煲仔饭", "aliases": "腊味煲仔饭", "kcal": 165, "protein": 6, "fat": 5, "carb": 24, "portion": 350},
  {"id": "dish_219", "cat": "dish", "name": "扬州炒饭", "aliases": "炒饭", "kcal": 180, "protein": 6, "fat": 6, "carb": 26, "portion": 300},
  {"id": "dish_220", "cat": "dish", "name": "皮蛋瘦肉粥", "aliases": "皮蛋粥", "kcal": 55, "protein": 3, "fat": 1.5, "carb": 7, "portion": 300},
  {"id": "dish_221", "cat": "dish", "name": "小笼包", "aliases": "南翔小笼", "kcal": 230, "protein": 9, "fat": 9, "carb": 28, "portion": 120},
  {"id": "dish_222", "cat": "dish", "name": "生煎包", "aliases": "生煎", "kcal": 245, "protein": 8, "fat": 10, "carb": 30, "portion": 100},
  {"id": "dish_223", "cat": "dish", "name": "锅贴", "aliases": "煎饺", "kcal": 240, "protein": 9, "fat": 10, "carb": 28, "portion": 100},
  {"id": "dish_224", "cat": "dish", "name": "担担面", "aliases": "重庆担担面", "kcal": 160, "protein": 6, "fat": 6, "carb": 22, "portion": 300},
  {"id": "dish_225", "cat": "dish", "name": "兰州拉面(清汤牛肉)", "aliases": "牛肉拉面", "kcal": 110, "protein": 5, "fat": 2.5, "carb": 17, "portion": 450},
  {"id": "dish_226", "cat": "dish", "name": "过桥米线", "aliases": "米线", "kcal": 120, "protein": 5, "fat": 3.5, "carb": 18, "portion": 400},
  {"id": "dish_227", "cat": "dish", "name": "麻辣烫(均估)", "aliases": "串串香均估", "kcal": 130, "protein": 7, "fat": 7, "carb": 10, "portion": 350},
  {"id": "dish_228", "cat": "dish", "name": "石锅拌饭", "aliases": "拌饭", "kcal": 150, "protein": 5, "fat": 5, "carb": 22, "portion": 350},
  {"id": "dish_229", "cat": "dish", "name": "咖喱鸡饭", "aliases": "咖喱饭", "kcal": 155, "protein": 7, "fat": 5, "carb": 22, "portion": 350},
  {"id": "dish_230", "cat": "dish", "name": "红烧狮子头", "aliases": "四喜丸子", "kcal": 220, "protein": 12, "fat": 16, "carb": 6, "portion": 150},
  {"id": "dish_231", "cat": "dish", "name": "锅包肉", "aliases": "锅包", "kcal": 230, "protein": 12, "fat": 12, "carb": 18, "portion": 150},
  {"id": "dish_232", "cat": "dish", "name": "蒜泥白肉", "aliases": "白肉", "kcal": 250, "protein": 15, "fat": 20, "carb": 2, "portion": 100},
  {"id": "dish_233", "cat": "dish", "name": "夫妻肺片", "aliases": "凉卤牛肉", "kcal": 190, "protein": 14, "fat": 13, "carb": 4, "portion": 100},
  {"id": "dish_234", "cat": "dish", "name": "口水鸡", "aliases": "凉拌鸡", "kcal": 170, "protein": 16, "fat": 11, "carb": 2, "portion": 120},
  {"id": "dish_235", "cat": "dish", "name": "凉拌木耳", "aliases": "葱油木耳", "kcal": 45, "protein": 1.5, "fat": 2.5, "carb": 4, "portion": 100},
  {"id": "dish_236", "cat": "dish", "name": "蒜蓉茄子", "aliases": "蒸茄子蒜蓉", "kcal": 70, "protein": 1.5, "fat": 4, "carb": 7, "portion": 180},
  {"id": "dish_237", "cat": "dish", "name": "豆角焖面", "aliases": "焖面", "kcal": 145, "protein": 5, "fat": 4, "carb": 23, "portion": 300},
  {"id": "dish_238", "cat": "dish", "name": "西红柿牛腩", "aliases": "番茄牛腩", "kcal": 130, "protein": 11, "fat": 6, "carb": 8, "portion": 250},
  {"id": "dish_239", "cat": "dish", "name": "酸辣白菜", "aliases": "炒白菜", "kcal": 55, "protein": 1.5, "fat": 3, "carb": 5, "portion": 150},
  {"id": "dish_240", "cat": "dish", "name": "香菇青菜", "aliases": "香菇菜心", "kcal": 40, "protein": 2, "fat": 2, "carb": 4, "portion": 150},
  {"id": "dish_241", "cat": "dish", "name": "玉米排骨汤", "aliases": "排骨汤", "kcal": 70, "protein": 5, "fat": 4, "carb": 3, "portion": 300},
  {"id": "dish_242", "cat": "dish", "name": "冬瓜排骨汤", "aliases": "排骨冬瓜", "kcal": 55, "protein": 4, "fat": 3, "carb": 2, "portion": 300},
  {"id": "dish_243", "cat": "dish", "name": "西湖牛肉羹", "aliases": "牛肉羹", "kcal": 50, "protein": 4, "fat": 2, "carb": 4, "portion": 250},
  {"id": "dish_244", "cat": "dish", "name": "虾仁滑蛋", "aliases": "滑蛋虾仁", "kcal": 140, "protein": 12, "fat": 9, "carb": 3, "portion": 150},
  {"id": "dish_245", "cat": "dish", "name": "干煸肥肠", "aliases": "肥肠", "kcal": 280, "protein": 12, "fat": 24, "carb": 4, "portion": 120},
  {"id": "dish_246", "cat": "dish", "name": "梅菜扣肉", "aliases": "扣肉", "kcal": 320, "protein": 12, "fat": 28, "carb": 6, "portion": 100},
  {"id": "dish_247", "cat": "dish", "name": "盐焗鸡", "aliases": "客家盐焗鸡", "kcal": 200, "protein": 18, "fat": 13, "carb": 2, "portion": 120},
  {"id": "dish_248", "cat": "dish", "name": "啤酒鸭", "aliases": "鸭块", "kcal": 210, "protein": 15, "fat": 15, "carb": 3, "portion": 150},
  {"id": "dish_249", "cat": "dish", "name": "孜然羊肉", "aliases": "烤羊肉串口味炒", "kcal": 250, "protein": 18, "fat": 18, "carb": 4, "portion": 120},
  {"id": "dish_250", "cat": "dish", "name": "青椒土豆丝", "aliases": "土豆丝炒青椒", "kcal": 90, "protein": 2, "fat": 4, "carb": 12, "portion": 150}
]
